language: ruby
bundler_args: --without development
before_script: "sh -e /etc/init.d/xvfb start && sudo aptitude -y -q install unzip chromium-browser"
script: "bundle exec rake travis"
rvm:
  - 1.9.3
branches:
  only:
    - master

