language: ruby
bundler_args: --without development
before_script: 
  - "sh -e /etc/init.d/xvfb start && sudo aptitude -y -q install unzip chromium-browser"
  - psql -c 'create role misadventure with createdb login; create database misadventure_test;' -U postgres
script: "bundle exec rake travis"
rvm:
  - 1.9.3
branches:
  only:
    - master

