common: &common
  adapter: postgresql
  username: misadventure
  password: misadventure # from psql setup, see Postgresql

development:
  <<: *common
  database: misadventure_development

test: &test
  <<: *common
  database: misadventure_test

production:
  <<: *common
  database: misadventure_production

cucumber:
  <<: *test
