common: &common
  adapter: postgresql
  username: misadventure

development:
  <<: *common
  database: misadventure_development

test: &test
  <<: *common
  database: misadventure_test

production:
  <<: *common
  database: misadventure_production

cucumber:
  <<: *test

#for travis-ci
postgres:
  <<: *test
  username: postgres
