common: &common
  adapter: postgresql
  username: postgres
  database: misadventure_<%=Rails.env%>

development:
  <<: *common

test: &test
  <<: *common

production:
  <<: *common

cucumber:
  <<: *test
